### ISSUE TITLE
Optional lab/notebook extension installation/enabling

### ISSUE THREAD

**Issue by marscher** [conda-forge/k3d-feedstock#26]
This is more of an meta-discussion on packaging. Since the conda package does not directly depend on either jupyter lab or notebook (indirectly on both because of ipywidgets), I wonder if it would be useful to provide two meta-packages for both notebook and lab users, which directly include the needed extensions.

For instance ipywidgets works out of the box without the need for the user to install/build/enable something else. Just installing the conda package is sufficient. It would be very much desirable if the k3d package would do the same thing.

**Comment by marscher** [comment]
Or this might be the solution: https://github.com/conda-forge/ipywidgets-feedstock/issues/58

**Comment by artur-trzesiok** [comment]
@marscher Thanks! Probably this is exactly the same topic like this one: https://github.com/K3D-tools/K3D-jupyter/issues/265#issuecomment-897798150 . We will try to do that

**Comment by marscher** [comment]
Thanks for the cref! I guess I should have looked in k3d orga first. I thought it would be merely a packaging issue, but I fear I'm wrong.

**Comment by artur-trzesiok** [comment]
It should be already done. I'm waiting for conda bot

**Comment by artur-trzesiok** [comment]
Hi. @marscher can you verify if latest conda 2.11.0 works good with that suggestion?

**Comment by marscher** [comment]
Now k3d makes a strict requirement on jupyterlab. Is that intended?

**Comment by marscher** [comment]
Ah sorry, the message is dynamically generated. It works as expected. But I will perform more tests.

**Comment by artur-trzesiok** [comment]
Thanks!

**Comment by marscher** [comment]
Thank you very much, everything works as expected now!
