### ISSUE TITLE
msgpack / msgpack-python dependency

### ISSUE THREAD

**Issue by CagtayFabry** [conda-forge/k3d-feedstock#28]
for version 2.10 `msgpack` is listed as a dependency in `setup.py`
https://github.com/K3D-tools/K3D-jupyter/blob/539c53cab580d55b8841bb87589ab3d4cf95bdb0/setup.py#L75-L82

however it is not currently listed in `meta.yaml` and not included when installing from conda
https://github.com/conda-forge/k3d-feedstock/blob/512e79bdbd66de2bd713b9637caf88f8a273dac7/recipe/meta.yaml#L23-L29

for conda this should probably list the `msgpack-python` package? (which is also suggested in the original PR under Dependency Analysis https://github.com/conda-forge/k3d-feedstock/pull/27)

just adding a ping here since not sure how active you are in this repo @artur-trzesiok

**Comment by artur-trzesiok** [comment]
Thanks! https://github.com/K3D-tools/K3D-jupyter/commit/57f95a9e0dd261748354c52137762db7e350987e
